name: Release

run-name: "Release: ${{ github.ref_name }}"

on:
    push:
        tags:
            - "v*"

jobs:
    build:
        name: Build
        permissions:
            contents: write
        uses: ./.github/workflows/build.yml
        with:
            ref: ${{ github.ref }}
            tag: ${{ github.ref_name }}
            update-version: false
            github-release: true

    publish:
        name: Publish
        needs: [build]
        runs-on: ubuntu-latest
        permissions:
            contents: write
            id-token: write
        steps:
            - name: Checkout Code
              uses: actions/checkout@v5
            - name: Setup Neon Environment
              uses: ./.github/actions/setup
              with:
                  use-rust: false
            - name: Fetch
              uses: robinraju/release-downloader@c39a3b234af58f0cf85888573d361fb6fa281534 # v1.10
              with:
                  tag: ${{ github.ref_name }}
                  fileName: "*.tgz"
                  out-file-path: ./dist
            - name: Publish
              shell: bash
              run: |
                  for p in ./dist/*.tgz ; do
                    npm publish --provenance --access public $p
                  done
